accounts/urls.py
from django.urls import path

from .views import SignupPageView

urlpatterns = [
    path("signup/", SignupPageView.as_view(), name="signup"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    # User management
    path("accounts/", include("django.contrib.auth.urls")),
    # Local apps
    path("accounts/", include("accounts.urls")),
    path("", include("hello.urls")),
    path("quiz/", include("quiz.urls")),
]

hello/urls.py
# hello/urls.py
from django.urls import path
from .views import HomeView, hello, HelloView, AboutView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("hello/", hello, name="hello"),
    path("helloWorld/", HelloView.as_view(), name="helloview"),
    path("about/", AboutView.as_view(), name="about"),
]

quiz/urls.py
from django.urls import path

from . import views

# app_name = 'quiz'
urlpatterns = [
    path('', views.QuizListView.as_view(), name='quiz_list'),
    path('<int:pk>/', views.QuizDetailView.as_view(), name='quiz_detail'),    
    path('<int:quiz_id>/submit/', views.submitView, name='submit'),
    path('<int:quiz_id>/<int:submission_id>/showresult/', views.show_quiz_result, name='show_quiz_result'),
 ] 
 

accounts/models.py
# accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    pass

hello/models.py
from django.db import models

# Create your models here.

quiz/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Quiz model
class Quiz(models.Model):
    name = models.CharField(max_length=200, default="name")
    description = models.TextField()

    def __str__(self):
        return f'title={self.name} content={self.description}' 

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question = models.TextField()
    score = models.IntegerField(default=0)

    def is_get_score(self, selected_ids):
        all_answers = self.choice_set.filter(is_correct=True).count()
        selected_correct = self.choice_set.filter(is_correct=True, id__in=selected_ids).count()
        if all_answers == selected_correct:
            return True
        else:
            return False

    def __str__(self):
        return f'question={self.question } score={self.score} quiz={self.quiz_id}'

class Choice(models.Model):
    choice = models.TextField()
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)
    order = models.IntegerField(default=0)
    rate = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(10)])

    class Meta:
        ordering = ['order']

    def __str__(self):
        return f'ID={self.id} order= {self.order} choice={self.choice} qeustion={self.question_id} is_correct={self.is_correct} rate={self.rate}'

class Submission(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    choices = models.ManyToManyField(Choice)

    def __str__(self):
        cstr = ','.join(str(c) for c in self.choices.all())
        return f'Submission: ID={self.id}; choices=[{cstr}]'

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "username",
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "username",
        )

accounts/views.py
from django.shortcuts import render

from django.urls import reverse_lazy
from django.views import generic

from .forms import CustomUserCreationForm


class SignupPageView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"
    

hello/views.py
from django.shortcuts import render

from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponse


class HomeView(TemplateView):
    template_name = "index.html"


def hello(request):
    return HttpResponse("Hello, World!")


class HelloView(TemplateView):
    template_name = "hello.html"

class AboutView(TemplateView):
    template_name = "about.html"

quiz/views.py
from cProfile import label
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse

from django.contrib.auth.models import User
import logging

from .models import Quiz, Question, Choice, Submission

logger = logging.getLogger('bootdj')

class QuizListView(ListView):
    template_name = 'quiz/quiz_list.html'
    context_object_name = 'quiz_list'

    def get_queryset(self):
        quizes = Quiz.objects.order_by('-id')[:10]
        return quizes

class QuizDetailView(DetailView):
    model = Quiz
    context_object_name = 'quiz'
    template_name = 'quiz/quiz_detail.html'

def submitView(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    user = request.user
    submission = Submission(quiz=quiz)
    submission.save()
    choices = extract_answers(request)
    submission.choices.add(*choices)
    logger.info(choices)

    return redirect('show_quiz_result', quiz_id=quiz_id, submission_id=submission.id)

def extract_answers(request):
    submitted_anwsers = []
    for key in request.POST:
        if key.startswith('choice'):
            choice_id = int(key.split('_')[1])
            choice_rate = int(request.POST[key])
            choice = Choice.objects.get(pk=choice_id)
            choice.rate = choice_rate
            choice.save()
            submitted_anwsers.append(choice)
    return submitted_anwsers

def show_quiz_result(request, quiz_id, submission_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    submission = Submission(id=submission_id)
    context = {}
    context['quiz'] = quiz
    choicesa = submission.choices.filter(question_id=1)
    choicesb = submission.choices.filter(question_id=2)

    # analytics
    la = [ca.rate for ca in choicesa]
    lb = [cb.rate for cb in choicesb]
    sl = [sum(value) for value in zip(la, lb)]

    roledict = {}
    for i in range(len(sl)):
        roledict[i+1] = sl[i]
    
    sorted_role = sorted(roledict.items(), key=lambda x: x[1], reverse=True)     
    context['sorted_role'] = sorted_role[:2]

    return render(request, 'quiz/quiz_result.html', context)

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}bootdj{% endblock title %}</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">  
  <!-- CSS -->
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark"><!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">bootdj</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Log In</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  <!-- JavaScript -->
  <script src="{% static 'js/base.js' %}"></script>
</body>
</html>

templates/about.html
{% extends "_base.html" %}

{% block title %}About{% endblock title %}

{% block content %}
  <h1>About Page</h1>
{% endblock content %}

templates/hello.html
<!doctype html>

<head></head>

<body>
    Hello World!
</body>

templates/index.html
{% extends "_base.html" %}
{% load static %}

{% block title %}Welcome to bootdj{% endblock title %}

{% block content %}
    <img class="The Coder" src="{% static 'images/coder.png' %}">
    <h1>Bootstrap framework for Django from Fred.</h1>

    {% if user.is_authenticated %}
        <p>Hi {{ user.name }}!</p>
        <p><a href="{% url 'logout' %}">Log Out</a></p>
    {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'login' %}">Log In</a>
    {% endif %}
{% endblock content %}

templates/quiz/quiz_detail.html
<!doctype html>
<html lang="en">
<head>
     {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
</head>

<body>
    <div class="container-fluid">
        <div class="alert alert-success">
            <h2>{{ quiz.name }}</h2>
            <form id="questionform" action="submit/" method="post">
                        {% for question in quiz.question_set.all %}
                        <div class="card mt-1">                            
                            <div class="card-header"><h5>{{question.question}}</h5></div>
                            {% csrf_token %}
                            <div class="form-group">
                               {% for choice in question.choice_set.all %}
                                <div class="form-check">
                                    <label class="form-check-label">
                                        <label for="choice">{{choice.order}}. {{choice.choice}} (Nubmer 0 to 10):</label><br>
                                        <input type="number" name="choice_{{choice.id}}"
                                                min="0" max="10" class="form-number-input" id="{{choice.id}}" value="0"}>
                                    </label>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                    <input class="btn btn-success btn-block" type="submit" value="Submit">
            </form> 
        </div>

    </body>
</html>

templates/quiz/quiz_list.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>Welceome to the QUIZ</title>
</head>
<body>
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                  <a class="navbar-brand" href="{% url 'quiz_list' %}">Welcome to Role Quiz</a>
            </div>
        </div>
    </nav>
    
    {% if quiz_list %}
        <div class="container">
            <div class="card-deck">
                {% for quiz in quiz_list %}
                    <div class="card" style="width: 36rem;">
                        <div class="card-body bg-light">
                              <h5 class="card-title">{{ quiz.name }} <span class="text-success">
                              <p class="card-text">{{ quiz.description}}</p>
                            <form action="{% url 'quiz_detail' quiz.id %}" method="get">
                                  {% csrf_token %}
                                  <input class="btn btn-primary"  type="submit"
                                         value="Take quiz">
                            </form>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <p>No quiz available.</p>
    {% endif %}
</body>
</html>

templates/quiz/quiz_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

<nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
        <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'quiz_list' %}">
                    <font color="blue">Take another Quiz</font></a>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="alert alert-success">
        <div class="card-columns-vertical mt-1">
        <h5 class="">Top 2 ranking roles for the candidate based on score:</h5>
            {% for r in sorted_role %}
            <div class="card mt-1">
                <div class="card-header"><h5>Role {{r.0}}</h5></div>
                <div class="card-header" ><font color="green">Score: {{r.1}}</font></div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="alert alert-success">
        <div class="card-columns-vertical mt-1">
        <h5 class="">Quiz Record: </h5>
            {% for question in quiz.question_set.all %}
            <div class="card mt-1">
                <div class="card-header"><h5>{{question.question}}</h5></div>
                {% for choice in question.choice_set.all %}
                    <div class="card-header" ><font color="green">{{choice.order}}. {{choice.choice}}: points={{choice.rate}}</font></div>
                {% endfor %}
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
        <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'quiz_list' %}">
                    <font color="blue">Take another Quiz</font></a>
        </div>
    </div>
</nav>

</body>
</html>